services:
  - type: web
    name: london-frontline-website
    env: node
    buildCommand: npm install
    startCommand: npm start
    plan: free
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production 